language: go

go:
  - 1.15.x

branches:
  only:
    - master

os:
  - linux
  - osx
  - windows

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      go test -timeout 300s -race -bench=. ./...;
    fi
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then
      go test -timeout 300s -bench=. ./...;
    fi

matrix:
  allow_failures:
    - os: osx
    - os: windows

